/*
** EPITECH PROJECT, 2024
** structure
** File description:
** texture.h
*/

#pragma once

#include "../includes/my_rpg.h"

typedef struct init_texture_s {
    sfTexture *background;
    sfTexture *play_grey_texture;
    sfTexture *play_white_texture;
    sfTexture *avertissment_texture;
    sfTexture *exit_red_texture;
    sfTexture *exit_white_texture;
    sfTexture *map_texture;
    sfTexture *text_press_texture;
    sfTexture *setting_black_texture;
    sfTexture *setting_white_texture;
    sfTexture *inventory_black_texture;
    sfTexture *inventory_white_texture;
    sfTexture *square_texture;
    sfTexture *square_texture_inventory;
    sfTexture *cross_black_texture;
    sfTexture *cross_white_texture;
    sfTexture *redexit_menu_texture;
    sfTexture *whiteexit_menu_texture;
    sfTexture *save_white_texture;
    sfTexture *save_grey_texture;
    sfTexture *high_sound_grey_texture;
    sfTexture *high_sound_white_texture;
    sfTexture *low_sound_grey_texture;
    sfTexture *low_sound_white_texture;
    sfTexture *volume_full_texture;
    sfTexture *volume_high_texture;
    sfTexture *volume_low_texture;
    sfTexture *volume_mute_texture;
    sfTexture *volume_mid_texture;
    sfTexture *texture_player;
    sfTexture *enemi_texture;
    sfTexture *player_combat_texture;
    sfTexture *combat_overlay_texture;
    sfTexture *combat_overlay_gris_texture;
    sfTexture *Attack_texture;
    sfTexture *buton_skill_texture;
    sfTexture *skill_texture;
    sfTexture *button_guards_texture;
    sfTexture *guard_texture;
    sfTexture *button_item_texture;
    sfTexture *item_texture;
    sfTexture *menu_combat_texture;
    sfTexture *menu_tete_texture;
    sfTexture *menu_bras_gauche_texture;
    sfTexture *menu_bras_droit_texture;
    sfTexture *menu_jambe_gauche_texture;
    sfTexture *menu_jambe_droite_texture;
    sfTexture *texte_tete_texture;
    sfTexture *tete_texture;
    sfTexture *bras_gauche_texture;
    sfTexture *bras_droit_texture;
    sfTexture *jambe_gauche_texture;
    sfTexture *jambe_droite_texture;
    sfTexture *life_barre_texture;
    sfTexture *save_session_texture;
    sfTexture *game_over_texture;
    sfTexture *texte_bras_gauche_texture;
    sfTexture *texte_bras_droit_texture;
    sfTexture *texte_jambe_gauche_texture;
    sfTexture *texte_jambe_droite_texture;
    sfTexture *donjon_one_texture;
    sfTexture *pnj_one_texture;
    sfTexture *press_e_texture;
    sfTexture *donjon_two_texture;
    sfTexture *interact_pnj_texture;
    sfTexture *press_sword_texture;
    sfTexture *ten_damage_texture;
    sfTexture *cross_black__inv_texture;
    sfTexture *cross_white_inv_texture;
    sfTexture *sword_inv_texture;
    sfTexture *pnj_two_texture;
    sfTexture *press_e_pnj_two;
    sfTexture *interact_eloi_texture;
    sfTexture *five_heal_texture;
    sfTexture *potion_inv_texture;
    sfTexture *press_potion_texture;
    sfTexture *background_fight_texture;
    sfTexture *draven_texture;
    sfTexture *press_e_draven;
    sfTexture *interact_draven_text;
    sfTexture *key_texture;
    sfTexture *press_e_key;
    sfTexture *interact_draven_two_text;
    sfTexture *shield_texture;
    sfTexture *press_e_shield;
    sfTexture *shield_inv_texture;
    sfTexture *shield_text_texture;
    sfTexture *enemi_two_texture;
    sfTexture *end_game_texture;
} texture_t;
